import Foundation
#if canImport(OSLog)
import OSLog
#endif

/// Pricing lookup against an embedded LiteLLM snapshot.
///
/// Plan A3: ship `pricing.json` as a bundle resource; refresh manually via
/// `tools/refresh-pricing.sh`. No network at runtime.
///
/// Plan A17 + A20: unknown models return `costUSD = 0` and surface in the
/// `unpricedModelTokens` map so the user can SEE the drift; we never throw.
public final class Pricing: @unchecked Sendable {

    public static let shared = Pricing()

    private let logger = Logger(subsystem: "com.clawdmeter.shared", category: "Pricing")

    /// Decoded model → ModelRates lookup, keyed by the exact LiteLLM model name.
    /// `nil` if the bundle resource couldn't be loaded.
    private let models: [String: ModelRates]
    private let modelKeys: [String]

    // MARK: - B3 LRU resolution cache
    //
    // Pre-B3: every `cost(for:tokens:)` call ran rates(for:) which does an
    // O(modelKeys.count) prefix scan on the resolution fallback path.
    // UsageHistoryLoader calls cost() once per record on cold loads of
    // multi-GB JSONL histories. With ~150 model keys in the snapshot, the
    // prefix scan dominates the cost-aggregation phase.
    //
    // B3 caches resolved rates keyed by the input model string. Repeat
    // lookups for the same model are O(1) — the common case in real
    // sessions where most records share a handful of models.
    //
    // Cache contains `Optional<ModelRates>` so we can memoize the
    // "unknown model" answer too (the prefix scan is wasted work for
    // unknown models on every record).
    //
    // Capacity is fixed at 256 entries — well above the realistic number
    // of distinct models a user observes in a single session. Eviction is
    // FIFO when capacity exceeds; simple + bounded memory.
    //
    // Thread-safety: `Pricing.shared` is global + @unchecked Sendable.
    // The cache is protected by an NSLock — fine grained: only one lock
    // hold per resolution, no I/O.
    //
    // Plan: B3 (Phase 2) — see
    // `.claude/plans/study-this-codebase-crystalline-shore.md`.
    private static let cacheCapacity = 256
    private let cacheLock = NSLock()
    private var resolutionCache: [String: ModelRates?] = [:]
    private var resolutionInsertionOrder: [String] = []

    /// Per-kind rates in $/token. `aboveBoundary` is non-nil for models with
    /// LiteLLM-tracked tiering (Claude past the 200k context boundary).
    public struct ModelRates: Sendable {
        public let inputPerToken: Decimal
        public let outputPerToken: Decimal
        public let cacheCreationPerToken: Decimal
        public let cacheReadPerToken: Decimal
        public let aboveBoundary: TierRates?
        public let boundaryTokens: Int
    }

    public struct TierRates: Sendable {
        public let inputPerToken: Decimal
        public let outputPerToken: Decimal
        public let cacheCreationPerToken: Decimal
        public let cacheReadPerToken: Decimal
    }

    public convenience init() {
        self.init(bundle: .module)
    }

    public init(bundle: Bundle) {
        // Load resource. Bundle.module is generated by SwiftPM for the
        // package; it points at the per-package resource bundle.
        guard let url = bundle.url(forResource: "pricing", withExtension: "json"),
              let data = try? Data(contentsOf: url) else {
            self.logger.error("Pricing: could not locate pricing.json in bundle")
            self.models = [:]
            self.modelKeys = []
            return
        }

        do {
            let payload = try JSONDecoder().decode(SnapshotPayload.self, from: data)
            var byKey: [String: ModelRates] = [:]
            for (key, raw) in payload.models {
                byKey[key] = Self.toModelRates(raw)
            }
            self.models = byKey
            self.modelKeys = Array(byKey.keys).sorted(by: { $0.count > $1.count })
            self.logger.info("Pricing loaded \(byKey.count, privacy: .public) models from \(payload._meta?.source ?? "unknown", privacy: .public)")
        } catch {
            self.logger.error("Pricing: decode error \(String(describing: error), privacy: .public)")
            self.models = [:]
            self.modelKeys = []
        }
    }

    // MARK: - Public API

    /// Cost of `tokens` consumed against `model`, in USD.
    ///
    /// Returns `0` for unknown models (rather than throwing) so the
    /// aggregation pipeline never aborts; the caller is responsible for
    /// surfacing unpriced-model token counts separately (`unpricedModelTokens`
    /// on `UsageHistorySnapshot`).
    ///
    /// v0.22.8 — ccusage parity rewrite. The previous implementation
    /// coupled the tier flip: once `inputTokens + cacheReadTokens > 200k`
    /// it switched **all** rates (input, output, cacheCreate, cacheRead)
    /// to the above-tier rate. That overcharged output / cache cost when
    /// only the input itself crossed the boundary. Upstream ccusage
    /// (`rust/crates/ccusage/src/cost.rs::tiered_cost`) splits **each
    /// token kind independently** at the 200k boundary against its OWN
    /// count. That's what we do now: per-kind `tiered_cost`, summed.
    ///
    /// The boundary is also a flat 200_000 constant — ccusage hard-codes
    /// `THRESHOLD: u64 = 200_000` and does not derive the boundary from
    /// `max_input_tokens` (which is per-model context window, not the
    /// pricing inflection). Reading `max_input_tokens` flipped the tier
    /// at 128k for some non-Claude models, silently undercharging.
    public func cost(for model: String, tokens: TokenTotals) -> Decimal {
        guard let rates = self.rates(for: model) else { return 0 }

        var total: Decimal = 0
        total += Self.tieredCost(
            count: tokens.inputTokens,
            base: rates.inputPerToken,
            above: rates.aboveBoundary?.inputPerToken
        )
        total += Self.tieredCost(
            count: tokens.outputTokens,
            base: rates.outputPerToken,
            above: rates.aboveBoundary?.outputPerToken
        )
        total += Self.tieredCost(
            count: tokens.cacheCreationTokens,
            base: rates.cacheCreationPerToken,
            above: rates.aboveBoundary?.cacheCreationPerToken
        )
        total += Self.tieredCost(
            count: tokens.cacheReadTokens,
            base: rates.cacheReadPerToken,
            above: rates.aboveBoundary?.cacheReadPerToken
        )
        // Reasoning tokens (codex / gpt-5 reasoning trace) are billed at
        // the same rate as output tokens on both providers per ccusage's
        // mapping. Apply the same per-kind tiered split.
        total += Self.tieredCost(
            count: tokens.reasoningTokens,
            base: rates.outputPerToken,
            above: rates.aboveBoundary?.outputPerToken
        )
        return total
    }

    /// Per-kind tiered cost matching ccusage's `tiered_cost`. First
    /// `BOUNDARY` of THIS kind's tokens billed at `base`, the rest billed
    /// at `above` when LiteLLM published a tier rate for this kind.
    /// When `above` is nil (most non-Claude kinds, output / cache for
    /// some models), the base rate applies to every token.
    @inlinable static func tieredCost(count: Int, base: Decimal, above: Decimal?) -> Decimal {
        guard count > 0 else { return 0 }
        guard let above else {
            return base * Decimal(count)
        }
        if count <= Self.tierBoundary {
            return base * Decimal(count)
        }
        let belowCount = Self.tierBoundary
        let aboveCount = count - belowCount
        return base * Decimal(belowCount) + above * Decimal(aboveCount)
    }

    /// ccusage hard-codes 200_000 as the inflection. Source:
    /// `rust/crates/ccusage/src/cost.rs:375` (`pub const THRESHOLD: u64 = 200_000;`).
    public static let tierBoundary: Int = 200_000

    /// Returns `true` when `model` resolves to a priced entry; `false` for
    /// unknown models. The aggregator uses this to decide whether to
    /// accumulate tokens into `unpricedModelTokens`.
    public func isPriced(_ model: String) -> Bool {
        rates(for: model) != nil
    }

    // MARK: - Lookup

    /// Find rates for a model name. Tries exact match, then strips a trailing
    /// dated suffix (`claude-sonnet-4-5-20250929` → `claude-sonnet-4-5`),
    /// then prefix-matches against the longest available LiteLLM key (so
    /// `gpt-5-codex-2026-02-01` would fall back to `gpt-5-codex` or `gpt-5`).
    ///
    /// B3 caches the result (success OR nil) per input string to avoid
    /// repeating the prefix scan on every record in a cold load.
    private func rates(for model: String) -> ModelRates? {
        // Fast path: cache hit (caches both success and unknown-model).
        cacheLock.lock()
        if let cached = resolutionCache[model] {
            cacheLock.unlock()
            return cached
        }
        cacheLock.unlock()

        // Cold path: run the original resolution.
        let resolved: ModelRates? = {
            if let exact = models[model] { return exact }
            let stripped = Self.stripDateSuffix(model)
            if stripped != model, let m = models[stripped] { return m }
            for candidate in modelKeys where model.hasPrefix(candidate) {
                return models[candidate]
            }
            return nil
        }()

        // Insert with FIFO eviction. Two writers might race here, but the
        // worst case is duplicate-then-discard work — never wrong answers.
        cacheLock.lock()
        if resolutionCache[model] == nil {
            resolutionCache[model] = resolved
            resolutionInsertionOrder.append(model)
            if resolutionInsertionOrder.count > Self.cacheCapacity {
                let evict = resolutionInsertionOrder.removeFirst()
                resolutionCache.removeValue(forKey: evict)
            }
        }
        cacheLock.unlock()
        return resolved
    }

    /// Drops the B3 LRU resolution cache. Exposed for tests + for
    /// downstream consumers that want to force re-resolution after
    /// the model catalog reloads (rare; the embedded snapshot is read
    /// once at app start). No-op in production.
    public func _resetResolutionCacheForTesting() {
        cacheLock.lock()
        resolutionCache.removeAll()
        resolutionInsertionOrder.removeAll()
        cacheLock.unlock()
    }

    private static func stripDateSuffix(_ name: String) -> String {
        // Strip `-YYYYMMDD` (Claude style) or `-YYYY-MM-DD` (OpenAI style).
        // Anchored at end so we don't accidentally chop mid-name.
        let patterns = [
            #"-\d{8}(-v\d+:\d+)?$"#,
            #"-\d{4}-\d{2}-\d{2}$"#,
        ]
        var out = name
        for pat in patterns {
            if let range = out.range(of: pat, options: .regularExpression) {
                out.removeSubrange(range)
                break
            }
        }
        return out
    }

    // MARK: - LiteLLM JSON decoding

    /// Top-level shape of `pricing.json`. Generated by `tools/refresh-pricing.sh`.
    private struct SnapshotPayload: Decodable {
        let _meta: Meta?
        let models: [String: RawModel]

        struct Meta: Decodable {
            let source: String?
            let capturedAt: String?
        }
    }

    /// Subset of LiteLLM's per-model schema that we actually use. Decoding is
    /// tolerant: missing fields default to 0, and we never throw on an unknown
    /// field shape.
    private struct RawModel: Decodable {
        let input_cost_per_token: Decimal?
        let output_cost_per_token: Decimal?
        let cache_creation_input_token_cost: Decimal?
        let cache_read_input_token_cost: Decimal?

        let input_cost_per_token_above_200k_tokens: Decimal?
        let output_cost_per_token_above_200k_tokens: Decimal?
        let cache_creation_input_token_cost_above_200k_tokens: Decimal?
        let cache_read_input_token_cost_above_200k_tokens: Decimal?

        let max_input_tokens: Int?
    }

    private static func toModelRates(_ raw: RawModel) -> ModelRates {
        let aboveBoundary: TierRates? = {
            // Tier rates only exist for Claude models in current LiteLLM; we
            // detect "has tier" via the input-above field.
            if let aboveInput = raw.input_cost_per_token_above_200k_tokens {
                return TierRates(
                    inputPerToken: aboveInput,
                    outputPerToken: raw.output_cost_per_token_above_200k_tokens ?? raw.output_cost_per_token ?? 0,
                    cacheCreationPerToken: raw.cache_creation_input_token_cost_above_200k_tokens ?? raw.cache_creation_input_token_cost ?? 0,
                    cacheReadPerToken: raw.cache_read_input_token_cost_above_200k_tokens ?? raw.cache_read_input_token_cost ?? 0
                )
            }
            return nil
        }()

        return ModelRates(
            inputPerToken: raw.input_cost_per_token ?? 0,
            outputPerToken: raw.output_cost_per_token ?? 0,
            cacheCreationPerToken: raw.cache_creation_input_token_cost ?? 0,
            cacheReadPerToken: raw.cache_read_input_token_cost ?? 0,
            aboveBoundary: aboveBoundary,
            // v0.22.8: pricing inflection is the literal 200k LiteLLM
            // threshold, NOT the per-model `max_input_tokens` context
            // window (those drift independently — e.g. gpt-5 context is
            // 128k but the pricing inflection doesn't apply to it at all).
            boundaryTokens: Pricing.tierBoundary
        )
    }
}
