import Foundation
import OSLog

/// Pricing lookup against an embedded LiteLLM snapshot.
///
/// Plan A3: ship `pricing.json` as a bundle resource; refresh manually via
/// `tools/refresh-pricing.sh`. No network at runtime.
///
/// Plan A17 + A20: unknown models return `costUSD = 0` and surface in the
/// `unpricedModelTokens` map so the user can SEE the drift; we never throw.
public final class Pricing: @unchecked Sendable {

    public static let shared = Pricing()

    private let logger = Logger(subsystem: "com.clawdmeter.shared", category: "Pricing")

    /// Decoded model → ModelRates lookup, keyed by the exact LiteLLM model name.
    /// `nil` if the bundle resource couldn't be loaded.
    private let models: [String: ModelRates]
    private let modelKeys: [String]

    /// Per-kind rates in $/token. `aboveBoundary` is non-nil for models with
    /// LiteLLM-tracked tiering (Claude past the 200k context boundary).
    public struct ModelRates: Sendable {
        public let inputPerToken: Decimal
        public let outputPerToken: Decimal
        public let cacheCreationPerToken: Decimal
        public let cacheReadPerToken: Decimal
        public let aboveBoundary: TierRates?
        public let boundaryTokens: Int
    }

    public struct TierRates: Sendable {
        public let inputPerToken: Decimal
        public let outputPerToken: Decimal
        public let cacheCreationPerToken: Decimal
        public let cacheReadPerToken: Decimal
    }

    public convenience init() {
        self.init(bundle: .module)
    }

    public init(bundle: Bundle) {
        // Load resource. Bundle.module is generated by SwiftPM for the
        // package; it points at the per-package resource bundle.
        guard let url = bundle.url(forResource: "pricing", withExtension: "json"),
              let data = try? Data(contentsOf: url) else {
            self.logger.error("Pricing: could not locate pricing.json in bundle")
            self.models = [:]
            self.modelKeys = []
            return
        }

        do {
            let payload = try JSONDecoder().decode(SnapshotPayload.self, from: data)
            var byKey: [String: ModelRates] = [:]
            for (key, raw) in payload.models {
                byKey[key] = Self.toModelRates(raw)
            }
            self.models = byKey
            self.modelKeys = Array(byKey.keys).sorted(by: { $0.count > $1.count })
            self.logger.info("Pricing loaded \(byKey.count, privacy: .public) models from \(payload._meta?.source ?? "unknown", privacy: .public)")
        } catch {
            self.logger.error("Pricing: decode error \(String(describing: error), privacy: .public)")
            self.models = [:]
            self.modelKeys = []
        }
    }

    // MARK: - Public API

    /// Cost of `tokens` consumed against `model`, in USD.
    ///
    /// Returns `0` for unknown models (rather than throwing) so the
    /// aggregation pipeline never aborts; the caller is responsible for
    /// surfacing unpriced-model token counts separately (`unpricedModelTokens`
    /// on `UsageHistorySnapshot`).
    ///
    /// Tiered models (Claude past 200k input tokens) apply the base rate to
    /// the first 200k input tokens and the above-boundary rate to the rest,
    /// per LiteLLM's convention. Cache and output rates also flip past the
    /// boundary when LiteLLM publishes tiered values for them.
    public func cost(for model: String, tokens: TokenTotals) -> Decimal {
        guard let rates = self.rates(for: model) else { return 0 }

        // Tiering split for input tokens. Models without an
        // `aboveBoundary` rate (most models, including non-Claude) use
        // the base rate for ALL tokens — the previous implementation
        // capped `belowInput` at `boundaryTokens` and only charged the
        // above portion when a tier rate existed, silently dropping
        // every input token past 200k for un-tiered models. Real bug:
        // a 915M-token Opus session was reading $0.60 of input cost
        // instead of $4.5k.
        let inputTokens = tokens.inputTokens
        let boundary = rates.boundaryTokens
        // P1-Shared-1 + Codex structured P2: cache-read tokens occupy the
        // same context-window budget as fresh input tokens, so they count
        // toward the tier boundary AND they consume part of the
        // below-tier allowance before fresh input does.
        //
        // For 150k input + 60k cache-read with a 200k boundary:
        //   total context = 210k → crosses boundary → hasAboveTier = true.
        //   cache-read fills the first 60k of the below-tier band.
        //   That leaves an effective below-tier ceiling for input of
        //     max(0, 200k - 60k) = 140k.
        //   inputBelow = min(150k, 140k) = 140k.
        //   inputAbove = 150k - 140k = 10k → billed at above-tier rate.
        //
        // The prior P1-Shared-1 patch correctly flipped hasAboveTier on
        // total context but split the input portion only on the raw
        // boundary, leaving inputAbove at 0 for this exact case and
        // silently undercharging the 10k that actually fell past the
        // effective boundary. Codex's structured pass caught the gap.
        let contextWindowTokens = inputTokens + tokens.cacheReadTokens
        let hasAboveTier = rates.aboveBoundary != nil && contextWindowTokens > boundary
        let aboveRates = rates.aboveBoundary

        var total: Decimal = 0
        if hasAboveTier, let above = aboveRates {
            let cacheReadBelow = min(tokens.cacheReadTokens, boundary)
            let effectiveBoundaryForInput = boundary > cacheReadBelow
                ? boundary - cacheReadBelow
                : 0
            let inputBelow = min(inputTokens, effectiveBoundaryForInput)
            let inputAbove = inputTokens - inputBelow
            total += rates.inputPerToken * Decimal(inputBelow)
            total += above.inputPerToken * Decimal(inputAbove)
        } else {
            // No tier flip — single rate applies to the full input count.
            total += rates.inputPerToken * Decimal(inputTokens)
        }

        // Output, cache-creation, cache-read: when the request crosses the
        // boundary we charge them at the above-tier rate when LiteLLM gives
        // us one. This matches ccusage's behavior — once you've crossed into
        // long-context billing, all the rates flip together.
        let crossedBoundary = hasAboveTier
        let outputRate = crossedBoundary ? (aboveRates?.outputPerToken ?? rates.outputPerToken) : rates.outputPerToken
        let cacheCreateRate = crossedBoundary ? (aboveRates?.cacheCreationPerToken ?? rates.cacheCreationPerToken) : rates.cacheCreationPerToken
        let cacheReadRate = crossedBoundary ? (aboveRates?.cacheReadPerToken ?? rates.cacheReadPerToken) : rates.cacheReadPerToken

        total += outputRate * Decimal(tokens.outputTokens)
        total += cacheCreateRate * Decimal(tokens.cacheCreationTokens)
        total += cacheReadRate * Decimal(tokens.cacheReadTokens)
        // Reasoning tokens are billed at the output rate on both providers.
        total += outputRate * Decimal(tokens.reasoningTokens)

        return total
    }

    /// Returns `true` when `model` resolves to a priced entry; `false` for
    /// unknown models. The aggregator uses this to decide whether to
    /// accumulate tokens into `unpricedModelTokens`.
    public func isPriced(_ model: String) -> Bool {
        rates(for: model) != nil
    }

    // MARK: - Lookup

    /// Find rates for a model name. Tries exact match, then strips a trailing
    /// dated suffix (`claude-sonnet-4-5-20250929` → `claude-sonnet-4-5`),
    /// then prefix-matches against the longest available LiteLLM key (so
    /// `gpt-5-codex-2026-02-01` would fall back to `gpt-5-codex` or `gpt-5`).
    private func rates(for model: String) -> ModelRates? {
        if let exact = models[model] { return exact }

        // Strip trailing date suffix (e.g. `-20250929`, `-2026-04-12`).
        let stripped = Self.stripDateSuffix(model)
        if stripped != model, let m = models[stripped] { return m }

        // Longest-prefix match against known keys.
        for candidate in modelKeys where model.hasPrefix(candidate) {
            return models[candidate]
        }
        return nil
    }

    private static func stripDateSuffix(_ name: String) -> String {
        // Strip `-YYYYMMDD` (Claude style) or `-YYYY-MM-DD` (OpenAI style).
        // Anchored at end so we don't accidentally chop mid-name.
        let patterns = [
            #"-\d{8}(-v\d+:\d+)?$"#,
            #"-\d{4}-\d{2}-\d{2}$"#,
        ]
        var out = name
        for pat in patterns {
            if let range = out.range(of: pat, options: .regularExpression) {
                out.removeSubrange(range)
                break
            }
        }
        return out
    }

    // MARK: - LiteLLM JSON decoding

    /// Top-level shape of `pricing.json`. Generated by `tools/refresh-pricing.sh`.
    private struct SnapshotPayload: Decodable {
        let _meta: Meta?
        let models: [String: RawModel]

        struct Meta: Decodable {
            let source: String?
            let capturedAt: String?
        }
    }

    /// Subset of LiteLLM's per-model schema that we actually use. Decoding is
    /// tolerant: missing fields default to 0, and we never throw on an unknown
    /// field shape.
    private struct RawModel: Decodable {
        let input_cost_per_token: Decimal?
        let output_cost_per_token: Decimal?
        let cache_creation_input_token_cost: Decimal?
        let cache_read_input_token_cost: Decimal?

        let input_cost_per_token_above_200k_tokens: Decimal?
        let output_cost_per_token_above_200k_tokens: Decimal?
        let cache_creation_input_token_cost_above_200k_tokens: Decimal?
        let cache_read_input_token_cost_above_200k_tokens: Decimal?

        let max_input_tokens: Int?
    }

    private static func toModelRates(_ raw: RawModel) -> ModelRates {
        let aboveBoundary: TierRates? = {
            // Tier rates only exist for Claude models in current LiteLLM; we
            // detect "has tier" via the input-above field.
            if let aboveInput = raw.input_cost_per_token_above_200k_tokens {
                return TierRates(
                    inputPerToken: aboveInput,
                    outputPerToken: raw.output_cost_per_token_above_200k_tokens ?? raw.output_cost_per_token ?? 0,
                    cacheCreationPerToken: raw.cache_creation_input_token_cost_above_200k_tokens ?? raw.cache_creation_input_token_cost ?? 0,
                    cacheReadPerToken: raw.cache_read_input_token_cost_above_200k_tokens ?? raw.cache_read_input_token_cost ?? 0
                )
            }
            return nil
        }()

        return ModelRates(
            inputPerToken: raw.input_cost_per_token ?? 0,
            outputPerToken: raw.output_cost_per_token ?? 0,
            cacheCreationPerToken: raw.cache_creation_input_token_cost ?? 0,
            cacheReadPerToken: raw.cache_read_input_token_cost ?? 0,
            aboveBoundary: aboveBoundary,
            boundaryTokens: raw.max_input_tokens ?? 200_000
        )
    }
}
