// E7: relay pairing bundle — the wire payload that travels via QR from
// Mac → iPhone at pairing time.
//
// Per docs/design/secure-relay-apns-2026-05-26.md §4.1, the Mac at pairing
// time:
//   - asks the relay Worker for a session ID and a (macTok, iosTok) bearer
//     pair (E2 already merged via PR #151);
//   - generates an X25519 ECDH keypair (ephemeral, in-memory only);
//   - encodes (sid, macTok, iosTok, macEcdhPub, ttl, relayUrl) into a QR
//     payload the iPhone scans;
//   - the iPhone parses the bundle, generates its own X25519 keypair,
//     derives the shared symmetric key via HKDF-SHA256, and persists it
//     locally.
//
// E7 SCOPE NOTE: this PR ships the QR payload + key-exchange wiring on
// both peers. It does NOT actually open the relay WebSocket — that's E3
// (Mac client) + E4 (iOS client). For E7, both peers stop at
// `keyExchanged` and the persisted symmetric key proves the handshake
// happened.
//
// WIRE-FORMAT PROVISIONAL NOTE: §4.1 of the design doc names CBOR as the
// long-term encoding; the doc is still in DRAFT pending security review.
// E7 ships **JSON-over-base64url** because (a) the doc isn't signed off
// on CBOR canonicalization yet, (b) JSON keeps the QR debuggable for
// support, and (c) the resulting payload (~250 bytes typical) stays
// well inside QR Version 9 capacity at error-correction level M. The
// fields are named identically to the doc (`sid`, `macTok`, `iosTok`,
// `ecdhPub`, `ttl`, `relayUrl`), so a CBOR migration is a wire-format
// flip and not a schema change. The `v` byte stays as a sentinel: a
// future v2 may switch to CBOR.

import Foundation

// MARK: - Wire-format types

/// Operator-issued grant authorizing the first peer to initialize a relay
/// Durable Object session. This is embedded in the QR bundle so the installed
/// Mac app does not need the relay operator signing key.
public struct RelaySessionCreationProof: Codable, Sendable, Equatable {
    public let issuedAtSeconds: UInt64
    public let nonce: String
    public let signature: String

    public init(issuedAtSeconds: UInt64, nonce: String, signature: String) {
        self.issuedAtSeconds = issuedAtSeconds
        self.nonce = nonce
        self.signature = signature
    }
}

/// QR-encoded pairing bundle that Mac displays + iPhone scans.
///
/// Field names mirror docs/design/secure-relay-apns-2026-05-26.md §4.1.
/// The encoded form is JSON wrapped in a `clawdmeter-pair://` URL — see
/// `RelayPairingBundle.encodeToURL(_:)` / `decode(fromURL:)`.
public struct RelayPairingBundle: Codable, Sendable, Equatable {

    /// Wire-format version. v1 = JSON-over-base64url; the design doc reserves
    /// the byte for future CBOR migration.
    public let v: Int

    /// Relay session ID — 32 random bytes, base64url-no-padding. E2's
    /// SESSION_ID_PATTERN (infra/relay/src/index.ts) requires 16-64 chars
    /// of `[A-Za-z0-9_-]`. Generated by the Mac at QR time.
    public let sid: String

    /// Mac peer's bearer token (32 random bytes, base64url). Mac presents
    /// this to the relay on its `?side=mac` WebSocket open. Per D22 the
    /// relay binds `(sid, macTok, side=mac)` together so a leaked QR
    /// cannot authorize the iOS side.
    public let macTok: String

    /// iOS peer's bearer token. Mac at QR time generates BOTH tokens and
    /// uploads their hashes to the relay as a signed `?bundle=` blob; the
    /// iPhone never uploads its own token hash — it only presents whatever it
    /// scanned.
    public let iosTok: String

    /// Mac's X25519 public key, base64url. iPhone uses this + its own
    /// ephemeral private key to derive the shared symmetric key.
    public let ecdhPub: String

    /// Absolute Unix seconds at which the relay rejects further connects.
    /// Mac's `RelayPairingService` currently sets this to `now + 30 days`.
    public let ttl: UInt64

    /// Base URL of the relay Worker — e.g. `wss://relay-staging.clawdmeter.dev`
    /// or `wss://relay.clawdmeter.dev`. iPhone uses this to know which
    /// host to dial in E4. Including it in the bundle (vs hard-coding)
    /// lets the operator point staging builds at a different relay
    /// without an iOS rebuild.
    public let relayUrl: String

    /// Relay Worker-signed proof for first-connect session creation. Optional
    /// for wire compatibility with old test vectors; current Mac pairing code
    /// populates it before displaying the QR.
    public let creationProof: RelaySessionCreationProof?

    /// Per-session APNS gateway bearer signing key, base64url encoded. The
    /// relay grants a key scoped to `(sid, Mac fingerprint)` during pairing so
    /// the Mac can sign gateway requests without a preseeded operator secret.
    public let apnsSigningKey: String?

    public init(
        v: Int = RelayPairingBundle.currentWireVersion,
        sid: String,
        macTok: String,
        iosTok: String,
        ecdhPub: String,
        ttl: UInt64,
        relayUrl: String,
        creationProof: RelaySessionCreationProof? = nil,
        apnsSigningKey: String? = nil
    ) {
        self.v = v
        self.sid = sid
        self.macTok = macTok
        self.iosTok = iosTok
        self.ecdhPub = ecdhPub
        self.ttl = ttl
        self.relayUrl = relayUrl
        self.creationProof = creationProof
        self.apnsSigningKey = apnsSigningKey
    }

    /// Bumped on any wire-incompatible change. v1 = JSON-over-base64url.
    public static let currentWireVersion: Int = 1

    // MARK: - URL form

    /// Custom-URL scheme the QR payload is wrapped in. We use a sibling
    /// scheme `clawdmeter-pair://` instead of overloading `clawdmeter://`
    /// so the legacy Tailscale pairing parser (PairingScannerView.parse)
    /// cleanly rejects relay payloads as a different kind, and vice
    /// versa.
    public static let urlScheme = "clawdmeter-pair"

    /// Encode this bundle as `clawdmeter-pair://v1/<base64url(JSON)>`.
    /// Base64url is used (no padding) so the URL is line-safe and works
    /// inside QR codes without any reserved-character issues.
    public func encodeToURL() throws -> String {
        let encoder = JSONEncoder()
        // Sorted keys means the JSON is byte-stable across Swift runs,
        // which keeps cross-platform test vectors comparable.
        encoder.outputFormatting = [.sortedKeys]
        let data = try encoder.encode(self)
        let b64 = RelayPairingBase64URL.encode(data)
        return "\(Self.urlScheme)://v\(self.v)/\(b64)"
    }

    /// Parse a `clawdmeter-pair://v1/<base64url>` URL into a bundle.
    /// Returns nil for any malformed input — never throws to the caller;
    /// the iOS scanner needs a yes/no decision per frame.
    ///
    /// Defenses (mirror PairingScannerView.parse rationale):
    ///   - Scheme must be `clawdmeter-pair`
    ///   - Version segment must match `v<int>` and be ≤ currentWireVersion
    ///   - Inner body must base64url-decode to a JSON object
    ///   - Every field must pass `validate()` (charset, length, TTL not
    ///     in the far future, relayUrl is wss://* or ws://localhost*).
    public static func decode(fromURL urlString: String) -> RelayPairingBundle? {
        guard let url = URL(string: urlString),
              url.scheme == Self.urlScheme else {
            return nil
        }
        // Path layout: //v1/<base64>
        // URL.host = "v1", URL.path = "/<base64>" (URL leaves the leading slash).
        guard let versionString = url.host,
              versionString.hasPrefix("v"),
              let scannedVersion = Int(versionString.dropFirst()),
              scannedVersion >= 1,
              scannedVersion <= Self.currentWireVersion else {
            return nil
        }
        let rawPath = url.path
        guard rawPath.hasPrefix("/") else { return nil }
        let body = String(rawPath.dropFirst())
        guard !body.isEmpty else { return nil }
        guard let data = RelayPairingBase64URL.decode(body) else { return nil }
        guard let bundle = try? JSONDecoder().decode(RelayPairingBundle.self, from: data) else {
            return nil
        }
        // Reject bundles whose decoded version disagrees with the
        // URL-segment version — defense in depth against a wedge where
        // the inner body claims v2 while the URL says v1.
        if bundle.v != scannedVersion { return nil }
        return bundle.validated()
    }

    /// Validate every field. Returns nil if anything is malformed; this
    /// is the trust boundary between "scanned bytes" and "trusted bundle".
    public func validated() -> RelayPairingBundle? {
        guard Self.isValidSessionId(sid) else { return nil }
        guard Self.isValidToken(macTok) else { return nil }
        guard Self.isValidToken(iosTok) else { return nil }
        guard macTok != iosTok else { return nil } // mirrors E2 isValidAuthBundle
        guard Self.isValidECDHPublicKey(ecdhPub) else { return nil }
        guard Self.isValidTTL(ttl) else { return nil }
        guard Self.isValidRelayURL(relayUrl) else { return nil }
        if let creationProof {
            guard Self.isValidCreationProof(creationProof) else { return nil }
        }
        if let apnsSigningKey {
            guard Self.isValidAPNSSigningKey(apnsSigningKey) else { return nil }
        }
        return self
    }

    // MARK: - Validation helpers

    /// E2 relay's session-id pattern is `^[A-Za-z0-9_-]{16,64}$`. We
    /// enforce the same on both sides so a malformed QR is rejected
    /// before any WS open is attempted in E3/E4.
    static func isValidSessionId(_ s: String) -> Bool {
        guard s.count >= 16, s.count <= 64 else { return false }
        return isBase64URLCharset(s)
    }

    /// Bearer tokens are 32-byte random → 43-char base64url. We accept
    /// 22-86 char tokens (covers shorter test fixtures + longer future
    /// budgets) on the same charset.
    static func isValidToken(_ s: String) -> Bool {
        guard s.count >= 22, s.count <= 86 else { return false }
        return isBase64URLCharset(s)
    }

    /// X25519 raw public keys are exactly 32 bytes → 43 chars base64url.
    static func isValidECDHPublicKey(_ s: String) -> Bool {
        // 32 bytes base64url-no-padding = 43 chars exactly.
        guard s.count == 43 else { return false }
        guard isBase64URLCharset(s) else { return false }
        // Must round-trip through the decoder and yield 32 bytes.
        guard let data = RelayPairingBase64URL.decode(s) else { return false }
        return data.count == 32
    }

    /// TTL must be in seconds (so a 4-digit year, ~10 digits), in the
    /// future, but not so far in the future that a clock-skew attack could keep
    /// a session usable indefinitely. CB-P0a (2026-06-05): the Mac now mints a
    /// 30-day session (durable transport), so the upper bound is 31 days — the
    /// 30-day mint plus a day of clock skew. A QR claiming a longer-than-31-day
    /// session is still rejected, capping a malicious/buggy bundle's window.
    static let maxTTLSeconds: UInt64 = 31 * 24 * 60 * 60  // 31 days (30d mint + skew)
    static func isValidTTL(_ ttl: UInt64) -> Bool {
        let now = UInt64(Date().timeIntervalSince1970)
        if ttl <= now { return false }
        if ttl > now + maxTTLSeconds { return false }
        return true
    }

    /// Relay URL must be `wss://` (production) or `ws://localhost*`
    /// (local dev). Anything else is rejected — the relay sits behind a
    /// known operator domain, and accepting an arbitrary scheme would
    /// let a malicious QR redirect the iPhone to an attacker's WS.
    static func isValidRelayURL(_ s: String) -> Bool {
        guard let url = URL(string: s),
              let scheme = url.scheme,
              let host = url.host else {
            return false
        }
        switch scheme {
        case "wss":
            // Allow any *.clawdmeter.dev plus a couple of escape hatches
            // for the test/dev ladder. We deliberately do NOT allow
            // arbitrary public hostnames — a QR pointing the iPhone at
            // attacker.example would otherwise be a free MITM.
            if host.hasSuffix(".clawdmeter.dev") { return true }
            if host == "clawdmeter.dev" { return true }
            if RelayEnvironment.isKnownHostedWorkerHost(host) { return true }
            return false
        case "ws":
            // Local-dev convenience: ws://localhost or ws://127.0.0.1
            // only. Same charset rules as PairingScannerView's loopback.
            return host == "localhost" || host == "127.0.0.1" || host == "::1"
        default:
            return false
        }
    }

    static func isValidCreationProof(_ proof: RelaySessionCreationProof) -> Bool {
        guard proof.issuedAtSeconds > 0 else { return false }
        guard proof.nonce.count >= 16, proof.nonce.count <= 128 else { return false }
        guard isBase64URLCharset(proof.nonce) else { return false }
        guard proof.signature.count >= 16, proof.signature.count <= 256 else { return false }
        return isBase64URLCharset(proof.signature)
    }

    static func isValidAPNSSigningKey(_ key: String) -> Bool {
        guard isBase64URLCharset(key),
              let decoded = RelayPairingBase64URL.decode(key) else {
            return false
        }
        return decoded.count >= 32
    }

    private static func isBase64URLCharset(_ s: String) -> Bool {
        for scalar in s.unicodeScalars {
            let v = scalar.value
            let isAlnum = (v >= 0x30 && v <= 0x39) || (v >= 0x41 && v <= 0x5A) || (v >= 0x61 && v <= 0x7A)
            let isUrlSafe = v == 0x2D || v == 0x5F // '-' or '_'
            if !(isAlnum || isUrlSafe) { return false }
        }
        return true
    }
}

// MARK: - Base64URL helper

/// Base64url-no-padding codec. CryptoKit's `Data(base64Encoded:)` only
/// handles standard base64; the relay design doc explicitly specifies
/// the URL-safe alphabet so the QR payload survives URL parsing.
public enum RelayPairingBase64URL {

    public static func encode(_ data: Data) -> String {
        let standard = data.base64EncodedString()
        return standard
            .replacingOccurrences(of: "+", with: "-")
            .replacingOccurrences(of: "/", with: "_")
            .replacingOccurrences(of: "=", with: "")
    }

    public static func decode(_ s: String) -> Data? {
        var padded = s
            .replacingOccurrences(of: "-", with: "+")
            .replacingOccurrences(of: "_", with: "/")
        let remainder = padded.count % 4
        if remainder > 0 {
            padded.append(String(repeating: "=", count: 4 - remainder))
        }
        return Data(base64Encoded: padded)
    }
}
